apiVersion: v1
kind: Service
metadata:
  name: color-api-clusterip
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
    - port: 80 # External port to access application from outside.
      targetPort: 80  # containerPort to run application inside container.


# clusterIP remains as the default type for services.