apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command:
        - 'sh'
        - '-c'
        # - 'echo "$username" && echo "$passowrd" && sleep 1800'
        # - 'sleep 1800'
      # env:
      #   - name: DB_USER
      #     valueFrom:
      #       secretKeyRef:
      #         key: username
      #         name: db-creds # name of the secret, created using CLI insted of manifest files.
      #   - name: DB_PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         key: password
      #         name: db-creds # name of the secret, created using CLI insted of manifest files.

      # envFrom:
      #   - secretRef:
      #       name: db-creds
              
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      volumeMounts:
        - name: db-secrets
          mountPath: /etc/db
  volumes:
    - name: db-secrets
      secret:
        secretName: db-creds
        items:  # if we want, we can specify every single key which we want to mount instead of entire file.
          - key: password
            path: dev/password


# remember when you mount secrets in the volumes as a file then it would be in the human readable form not in base64 string.

# kubectl create secret generic db-creds --from-literal=username=db_user --from-literal=password=db_pass